### ISSUE TITLE
Maturity of project

### ISSUE THREAD

**Issue by WonderCsabo** [m0er/androidannotations-custom-plugin#1]
Hey,

We want to include the AA plugins in our main wiki. How mature is project? I guess it is not deployed to a central repository. Do you intend to distribute it?

**Comment by m0er** [comment]
Hi, @WonderCsabo. I really appreciate your suggestion. I have a plan to improve my project more detail. I'd like to suggest to deploy after more improvement work. I will inform you immediately if done. Would you like to wait for a little more time (a week maybe)?

**Comment by WonderCsabo** [comment]
Of course, no rush! I will add the plugin to our list once it reaches a central repo, and it is considered to be have a stable version.

**Comment by m0er** [comment]
Hey @WonderCsabo. I think I'm done. Is it ok to publish JitPack instead of central repo?
Please let me know any suggestions or issues!

**Comment by WonderCsabo** [comment]
JitPack is okay of course. One thing: you could add JavaDoc to your annotation.

I added this plugin to the AA wiki!

**Comment by m0er** [comment]
Thanks! I'll do it soon.
